config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  root 'home#index'
  resources :boats
  resources :boat_jobs
  resources :customers
  resources :jobs
  resources :companies
  resources :posts

get 'logout' => "home#logout"
get 'dashboard' => "home#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
	

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @company = Company.new
    end
  def dashboard
  	@jobs = Job.all
  	@boats = Boat.all
  end
def logout

	session[:company_id] = nil
	flash[:message] = "You are logged out !"
	redirect_to :root



end

  end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<p id="notice"><%= notice %></p>
<ul>
	  <li><a class="active" href="/">HOME</a></li>

	   <% if company_signed_in? %>
	  	<li id="navRight_style"><%= link_to('logout', destroy_company_session_path, method: :delete) %></li>
			<li id="navRight_style"><a href="#"><%= current_company.email %></a></li>
  		<li><a href="/dashboard">dashboard</a></li>
			<li><a href="/boats">boats</a></li>
	  <% else %>

	  	<li id="navRight_style"><%= link_to "login", new_company_session_path %></li>
     	<li id="navRight_style"><%= link_to"signup", new_company_registration_path %> </li>

	  <% end %>
  </ul>

app/views/home/dashboard.html.erb
<div  class="section_heading">
<h1 class= "section-heading" style="color:brown;font-size:300%;font-family:'Contrail One',cursive;">My Dashboard</h1>

<i class="fa fa-user-circle fa-3x" aria-hidden="true"></i>

<table id="dashboard_style">
  <thead>
    <tr>
 <th class= "section-heading" style="color:black;font-size:100%;font-family:'Contrail One',cursive;">My Boat Fleet</th>

 <% @boats.each do |boat| %>

   <th><%= boat.name %></th>
   <% end %>
</tr>
<tr>
       <th class= "section-heading" style="color:black;font-size:100%;font-family:'Contrail One',cursive;">My Shipments</th>


       	<% @jobs.each do |jobs| %>

       		<th><%= jobs.id %></th>
       		<th><%= jobs.status %></th>
       		<% end %>
</tr>
<tr>

<%= current_company.email %>
 <th colspan="3"></th>
   </tr>
 </thead>
</div>
 <tbody>
</tbody>
</table>

<%= link_to new_job_path do %>

<span class="fa-stack fa-4x" style="color:brown;">
<i class="fa fa-anchor" aria-hidden="true"></i>
<button id="newBoatbutton" class="btn btn-primary btn-xl text-uppercase" type="submit">New Shipment</button>

</span>

<% end %>

<%= link_to new_boat_path do %>

        <span class="fa-stack fa-4x" style="color:brown;">
        <i class="fa fa-anchor" aria-hidden="true"></i>
  <button id="newBoatbutton" class="btn btn-primary btn-xl text-uppercase" type="submit">New Boat</button>

        </span>

        <% end %>

        <%= link_to root_path do %>

                <span class="fa-stack fa-4x" style="color:brown;">
                <i class="fa fa-anchor" aria-hidden="true"></i>
          <button id="newBoatbutton" class="btn btn-primary btn-xl text-uppercase" type="submit">Home</button>

                </span>

                <% end %>

app/views/home/index.html.erb
<!-- Header -->

<!-- Services -->

<div class="section_heading">
<section id="home_style">



        <h2 class="section-heading" style="color:brown;font-size:300%;font-family:'Contrail One',cursive;">Shipped</h2>

        <img src="http://aaronchang.com/wp-content/uploads/images/products/p-19177-4120_Sailboats_1738_1000px_web.jpg" class="img-fluid" alt="Responsive image">
        <h3 class="section-subheading text-muted" style="color:grey;font-size:200%;font-family:'Contrail One',cursive;">We will ship your stuff anywhere!</h3>

<%= link_to new_company_path do %>
        <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Sign Up to Continue</button>
<% end %>

<% if company_signed_in? %>
  <%= link_to destroy_company_session_path, method: :delete do %>
          <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Logout</button>
  <% end %>
<% else %>
  <%= link_to new_company_session_path do %>
          <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Login</button>
  <% end %>
<% end %>

  </div>

    <br></br>

    <div class="row text-center">
      <div class="col-md-4">


        <span class="fa-stack fa-4x" style="color:brown;">
        <i class="fa fa-anchor" aria-hidden="true"></i>

        </span>


        <h4 class="service-heading"style="color:black;font-size:300%;font-family:'Contrail One',cursive;">Boat Fleet</h4>
        <p class="text-muted" style="color:grey;font-size:200%;font-family:'Contrail One',cursive;">view boats or create your own</p>
      </div>
      <div class="col-md-4">


        <span class="fa-stack fa-4x" style="color:brown;">
        <i class="fa fa-anchor" aria-hidden="true"></i>


        </span>


        <h4 class="service-heading"style="color:black;font-size:300%;font-family:'Contrail One',cursive;">Locations</h4>
        <p class="text-muted" style="color:grey;font-size:200%;font-family:'Contrail One',cursive;">pick a location to ship your cargo</p>
      </div>
      <div class="col-md-4">


        <span class="fa-stack fa-4x" style="color:brown;">
        <i class="fa fa-anchor" aria-hidden="true"></i>

        </span>

        <h4 class="service-heading" style="color:black;font-size:300%;font-family:'Contrail One',cursive;">Boat Shipments</h4>
        <p class="text-muted" style="color:grey;font-size:200%;font-family:'Contrail One',cursive;">pick a boat size that fits your needs </p>
      </div>
    </div>
  </div>
</div>