config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  root 'home#index'
  resources :boats
  resources :boat_jobs
  resources :customers
  resources :jobs
  resources :companies
  resources :posts

get 'logout' => "home#logout"
get 'dashboard' => "home#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
	

app/models/boat.rb
class Boat < ApplicationRecord

belongs_to :company
has_many :boat_jobs
has_many :jobs, :through => :boat_jobs

has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ""
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

validates :name , :uniqueness => true

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end



  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)
    @boat.company_id = current_company.id

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :size, :max_load, :photo, :assign_jobs)
    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.erb
<%= form_with(model: boat, local: true) do |form| %>
  <% if boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :boat_name %>
  </div>

  <div class="field">
    <%= form.label :size %>

    <%=form.select :size , options_for_select([
    ['Small (500 Max)'], ['Medium (1000 Max)'],['large(2000 Max)' ]] )%>
  </div>

<!--

    <%=form.select options_for_select([
    ['Small', 1], ['Medium', 2],['large, 3 '] ] )%>
  </div>


  <div class="field">
    <%= form.label :max_load %>
    <%= form.text_field :max_load, id: :boat_max_load %>
  </div> -->

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :photo%>
  </div>





  <!-- <div class="field">
    <%= form.label :assign_jobs %>
    <%= form.number_field :assign_jobs, id: :boat_assign_jobs %>
  </div> -->

  <div class="field">
    <%= form.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>
<div class="section_heading">
<h1 class= "section-heading" style="color:brown;font-size:300%;font-family:'Contrail One',cursive;">Boats</h1>

<div class="section_heading">
<table id="boat_style">
  <thead>
    <tr>

      <th>Name</th>
      <th>Size</th>
      <th>Max load</th>
      <th>Image url</th>
      <th>Assign jobs</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
</div>
    </div>

    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        <td><%= boat.size %></td>
        <td><%= boat.max_load %></td>
        <td><%= image_tag boat.photo.url (:medium)%></td>
        <td><%= boat.assign_jobs %></td>

        <td><%= link_to 'Show', boat %></td>

        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>

        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to new_boat_path do %>

        <span class="fa-stack fa-4x" style="color:brown;">
        <i class="fa fa-anchor" aria-hidden="true"></i>
  <button id="newBoatbutton" class="btn btn-primary btn-xl text-uppercase" type="submit">New Boat</button>

        </span>

        <% end %>

app/views/boats/new.html.erb
<div class="section_heading">
<h1 class= "section-heading" style="color:brown;font-size:300%;font-family:'Contrail One',cursive;">New Boat</h1>
</div>
<%= render 'form', boat: @boat %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boat.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @boat.size %>
</p>

<p>
  <strong>Max load:</strong>
  <%= @boat.max_load %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @boat.photo.url (:medium)%>
</p>

<p>
<h1><strong>Assign jobs:</strong></h1>
  <%= @boat.assign_jobs %>
<%= link_to 'Create Job for this Boat', new_job_path  %>

<br>
<br>
<br>
<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>